spring:
    application:
        name: "service-halloWelt"

info:
    fsl:
      servicename: '@fsl-servicename@'
      servicegroup: '@fsl-servicegroup@'
    spring:
      application:
        name: "service-halloWelt"
    maven:
        group: '@project.groupId@'
        artifact: '@project.artifactId@'
        description: '@project.description@'
        version: '@project.version@'

endpoints:
  health.sensitive: false

mbean:
    filter:
      uriRegexes:
          - /info
          - /hallo/.*^/hallo/{msg}

---
spring:
  profiles: lokal
server:
    port: 11111
eureka:
  instance:
    preferIpAddress: true
  client:
    enabled: false
# ab hier alle Properties einfuegen, die fuer unittests im Profil lokal genutzt werden sollen
# dran denken, die Properties bei zeiten auch auf den configserver einzutragen!
