server:
  port: 8888

# use local file system
spring:
    cloud:
        config:
            server:
                native:
                    search-locations: classpath:/configrepo
                    # if search locations is not given it is the same as Spring boot
#                   # i.e. [classpath:/, classpath:/configrepo, file:./, file:./configrepo] e.g. for files => file:\\\C:\Users\fsubasi\Desktop\configrepo-repo\
    profiles:
       # 'native' profile in the Config Server doesn't use Git, but just loads the configrepo files
       # from the local classpath or file system
       active: native

# use git
#spring:
#  cloud:
#    configrepo:
#      server:
#        git:
   #       uri: https://github.com/sullafelix/config-repo
          # searchPaths: foo,bar*  => search foo and any subdirectory that begins with bar for configrepo files (example in infrastructure-configserver bootstrap.yml file)



