spring:
  application:
    name: users-service # Service registers unter this name


# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 2222 # HTTP (Tomcat) port